apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-checker-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-checker-flask
  template:
    metadata:
      labels:
        app: website-checker-flask
    spec:
      containers:
      - name: web
        image: website-checker-flask
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: website-checker-service
spec:
  selector:
    app: website-checker-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
