# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret  # Имя нашего секрета, чтобы потом на него ссылаться
type: Opaque  # Стандартный тип для пар ключ-значение
data:
  # Пароль для пользователя БД. Команда 'echo -n "ваш_пароль" | base64'
  # ЗАМЕНИ 'mysecretpassword' на свой надежный пароль!
  password: bXlzZWNyZXRwYXNzd29yZA==  # Это 'mysecretpassword' в base64
